### ISSUE TITLE
`index_not_found` when overriding `index_name`

### ISSUE THREAD

**Issue by soulshake** [ikollipara/django-meili#5]
Hello, and thanks for this useful library!

When I modify my model (e.g. `Place`) to inherit from `IndexMixin` and override `MeiliMeta.index_name` (e.g. ` f"{settings.DJANGO_ENV}_Place"`, the app fails to start with:

```
MeilisearchApiError: MeilisearchApiError. Error code: index_not_found. Error message: Index `Place` not found. Error documentation: https://docs.meilisearch.com/errors#index_not_found Error type: invalid_request
```

<details>

<summary>Full traceback</summary>

```
2024-06-22 14:01:31 [connectionpool.py:474] urllib3.connectionpool DEBUG https://search.example.com:443 "GET /indexes/Place HTTP/1.1" 404 None
Traceback (most recent call last):
  File "/home/me/git/repos/example.com/venv/lib/python3.11/site-packages/meilisearch/_httprequests.py", line 135, in __validate
    request.raise_for_status()
  File "/home/me/git/repos/example.com/venv/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://search.example.com:443/indexes/Place

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/me/git/repos/example.com/www/./manage.py", line 56, in <module>
    main()
  File "/home/me/git/repos/example.com/www/./manage.py", line 34, in main
    django.setup()
  File "/home/me/git/repos/example.com/venv/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/me/git/repos/example.com/venv/lib/python3.11/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/home/me/git/repos/example.com/venv/lib/python3.11/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/me/git/repos/example.com/venv/lib/python3.11/site-packages/ddtrace/internal/module.py", line 220, in _exec_module
    self.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/me/git/repos/example.com/www/catalog/models.py", line 111, in <module>
    from places.models import Marker, Place
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/me/git/repos/example.com/venv/lib/python3.11/site-packages/ddtrace/internal/module.py", line 220, in _exec_module
    self.loader.exec_module(module)
  File "/home/me/git/repos/example.com/www/places/models.py", line 186, in <module>
    class Place(
  File "/home/me/git/repos/example.com/venv/lib/python3.11/site-packages/django/db/models/base.py", line 120, in __new__
    new_class = super_new(cls, name, bases, new_attrs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/git/repos/example.com/venv/lib/python3.11/site-packages/django_meili/models.py", line 103, in __init_subclass__
    cls.meilisearch = IndexQuerySet(cls)
                      ^^^^^^^^^^^^^^^^^^
  File "/home/me/git/repos/example.com/venv/lib/python3.11/site-packages/django_meili/querysets.py", line 40, in __init__
    self.index = _client.get_index(model.__name__)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/git/repos/example.com/venv/lib/python3.11/site-packages/meilisearch/client.py", line 181, in get_index
    return Index(self.config, uid).fetch_info()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/git/repos/example.com/venv/lib/python3.11/site-packages/meilisearch/index.py", line 131, in fetch_info
    index_dict = self.http.get(f"{self.config.paths.index}/{self.uid}")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/git/repos/example.com/venv/lib/python3.11/site-packages/meilisearch/_httprequests.py", line 76, in get
    return self.send_request(requests.get, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/git/repos/example.com/venv/lib/python3.11/site-packages/meilisearch/_httprequests.py", line 68, in send_request
    return self.__validate(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/git/repos/example.com/venv/lib/python3.11/site-packages/meilisearch/_httprequests.py", line 138, in __validate
    raise MeilisearchApiError(str(err), request) from err
meilisearch.errors.MeilisearchApiError: MeilisearchApiError. Error code: index_not_found. Error message: Index `Place` not found. Error documentation: https://docs.meilisearch.com/errors#index_not_found Error type: invalid_request
```
</details>

I would instead expect the index `<DJANGO_ENV>_Place` to be created. (If I don't override `index_name`, then an index called `Place` is created automatically.)

I believe the issue is caused by this line:

https://github.com/ikollipara/django-meili/blob/edd7fe2ece14b7d1a8211d1f7009f2149e0c3d06/django_meili/querysets.py#L40

When I replaced the line as follows, the app starts as expected:

```
self.index = _client.get_index(model.MeiliMeta.index_name or model.__name__)
```

At first I thought it might be because I didn't have `django_meili` at the top of `INSTALLED_APPS`, but it still happens when it's in the first position.

Happy to submit a pull request if my fix above would be appropriate!

**Comment by ikollipara** [comment]
Thanks for the feedback, that definitely slipped my mind when writing the tests. I've added a new test case to check for that, and it should all work! Version 0.4 should fix this issue.
