### ISSUE TITLE
Global toggle to disable Meilisearch network calls?

### ISSUE THREAD

**Issue by soulshake** [ikollipara/django-meili#6]
I'm observing that every time I run Django (whether it's `runserver` or a management command), there are 7 network requests made to my Meilisearch host for each index I've defined:

```
Starting new HTTPS connection (1): search.example.com:443
https://search.example.com:443 "GET /indexes HTTP/1.1" 200 None
Starting new HTTPS connection (1): search.example.com:443
https://search.example.com:443 "POST /indexes HTTP/1.1" 202 None
Starting new HTTPS connection (1): search.example.com:443
https://search.example.com:443 "PUT /indexes/development_Place/settings/displayed-attributes HTTP/1.1" 202 None
Starting new HTTPS connection (1): search.example.com:443
https://search.example.com:443 "PUT /indexes/development_Place/settings/searchable-attributes HTTP/1.1" 202 None
Starting new HTTPS connection (1): search.example.com:443
https://search.example.com:443 "PUT /indexes/development_Place/settings/filterable-attributes HTTP/1.1" 202 None
Starting new HTTPS connection (1): search.example.com:443
https://search.example.com:443 "PUT /indexes/development_Place/settings/sortable-attributes HTTP/1.1" 202 None
Starting new HTTPS connection (1): search.example.com:443
https://search.example.com:443 "GET /indexes/development_Place HTTP/1.1" 200 None
```

I would like to be able to only make these calls when certain conditions are met. For example, I want to bypass them entirely if my app settings contain `OFFLINE = True`.

I can't see a way to do it with the current implementation. I tried subclassing `IndexMixin` and overriding `__init_subclass__`:

```
from django_meili.models import IndexMixin

class MeiliToggleIndexMixin(IndexMixin):
    class MeiliMeta:
        filterable_fields = None
        searchable_fields = None
        displayed_fields = None

    def __new__(cls, *args, **kwargs) -> None:
        print("In MeiliToggleIndexMixin.__new__")

    def __init_subclass__(cls, *args, **kwargs) -> None:
        print("In MeiliToggleIndexMixin.__init_subclass__")

    def __init__(cls, *args, **kwargs) -> None:
        print("In MeiliToggleIndexMixin.__init__")


class Place(MeiliToggleIndexMixin, models.Model):
    ...
```

...but it doesn't seem to work; after modifying [`django_meili/models.py`](https://github.com/ikollipara/django-meili/blob/7c908da11c9e96a098ad5415274ce0202572caeb/django_meili/models.py#L86) as follows:

```
class IndexMixin(models.Model):
    def __init_subclass__(cls) -> None:
        raise RuntimeError("should not be here")
```

...it seems Django is explicitly calling `__new__` on the parent class:

```
./manage.py showmigrations

[...]

Traceback (most recent call last):
  File "/home/me/git/example.com/www/./manage.py", line 56, in <module>
    main()
  File "/home/me/git/example.com/www/./manage.py", line 34, in main
    django.setup()
  File "/home/me/git/example.com/venv/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/me/git/example.com/venv/lib/python3.11/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/home/me/git/example.com/venv/lib/python3.11/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/me/git/example.com/venv/lib/python3.11/site-packages/ddtrace/internal/module.py", line 220, in _exec_module
    self.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/me/git/example.com/www/catalog/models.py", line 111, in <module>
    from places.models import Marker, Place
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/me/git/example.com/venv/lib/python3.11/site-packages/ddtrace/internal/module.py", line 220, in _exec_module
    self.loader.exec_module(module)
  File "/home/me/git/example.com/www/places/models.py", line 26, in <module>
    from catalog.meili import MeiliToggleIndexMixin
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/me/git/example.com/venv/lib/python3.11/site-packages/ddtrace/internal/module.py", line 220, in _exec_module
    self.loader.exec_module(module)
  File "/home/me/git/example.com/www/catalog/meili.py", line 10, in <module>
    class MeiliToggleIndexMixin(IndexMixin):
  File "/home/me/git/example.com/venv/lib/python3.11/site-packages/django/db/models/base.py", line 120, in __new__
    new_class = super_new(cls, name, bases, new_attrs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/git/example.com/venv/lib/python3.11/site-packages/django_meili/models.py", line 87, in __init_subclass__
    raise RuntimeError("should not be here")
RuntimeError: should not be here
```

Is there a way to achieve this global toggle behavior I'm looking for?

(On a semi-related note, I don't know how subclassing `IndexMixin` could work at all, because then django-meili treats the immediate subclass as its own index, rather than the grandchild class. Maybe there's a Python mechanism I'm not aware of that could help with this?)

**Comment by ikollipara** [comment]
Hey, what you're saying makes a lot of sense and based on the implementation in `django_meili/models.py` it sends a different statement for each of those updated aspects. I think a way to bundle those requests isn't a bad idea at all, but I haven't seen anything on their docs that supports that.

In regards to the python issue, I don't think you're calling `super()` for any of the subclassed methods. That means you aren't allowing the default behavior to take place.

**Comment by ikollipara** [comment]
I've added an option to the settings of the application (documented on the README) that enables offline mode as you described. In addition, I've cleaned up the requests so that only two are made per model.

1. To create the index
2. To sync all settings
